---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook
  namespace: pod-name-wh
spec:
  secretName: cert-webhook
  duration: 8760h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-ca
  dnsNames:
  - pod-name-wh.pod-name-wh.svc
  - pod-name-wh.pod-name-wh
  - pod-name-wh
